
{{- range $tlsSecretName, $tlsSecret := .Values.tlsSecrets }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $tlsSecretName }}
data:
  tls.crt: {{ $tlsSecret.certificate | b64enc }}
  tls.key: {{ $tlsSecret.key | b64enc }}
{{- end }}