#!/bin/bash

WS_VALUES_EMAIL=""
WS_VALUES_EMAIL_PASS=""
WS_VALUES_USER=""
WS_VALUES_PASS=""
WS_VALUES_PROXY=""
WS_VALUES_DOMAIN=""

CONST_VARS=(
    WS_VALUES_EMAIL_PASS
    WS_VALUES_EMAIL
    WS_VALUES_USER
    WS_VALUES_PASS
    WS_VALUES_PROXY
    WS_VALUES_DOMAIN
)

